# Generated by Django 5.0 on 2023-12-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventslot',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event_slots/'),
        ),
    ]
